spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
hibernate:
  hbm2ddl:
    auto: create-drop
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: 'true'
conversion:
  margin: '2.0'
